### PR TITLE
Add the exec options to the README

### LINKED ISSUE #50: The 'options' property needs adding to the README
https://github.com/jharding/grunt-exec/issues/22 / https://github.com/jharding/grunt-exec/pull/45 added support for the 'options' property, however this isn't referenced in the README:
https://github.com/jharding/grunt-exec/blob/master/README.md#properties

### PR DESCRIPTION
**Pull request by dandv**
Fix #50

### CODE REVIEW

**Comment by edmorley** [comment]
@jharding, could you merge this? :-)

**Comment by fabiancz** [comment]
@jharding please merge this! It takes me long time to figure out how to encrease maxBuffer!

I think it also resolves issue #23 and #64.

**Comment by jonnor** [comment]
Can you please merge this? Also struggled to find docs on this

**Comment by arnaudvalle** [comment]
:+1: - would be good to get this merged. I came across the same sort of problem and tweaking the maxBuffer option was the solution

**Comment by lee-reinhardt** [comment]
Thankfully google directed me here. Merging this would be very helpful.

**Comment by gwicksted** [comment]
Added to README with latest Node documentation

**Pull request closed without merging**
