### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by TheSavior** [comment]
Please merge this. Now that 1.0.0 has been released, this is breaking builds.

**Comment by DennisBecker** [comment]
I also need this patch, otherwise will fork this and patch it myself.

**Comment by Miw0** [comment]
Anyone even active here? :troll:

**Comment by AtiX** [comment]
+1

**Comment by jordanluyke** [comment]
+1

**Comment by sbruton** [comment]
+1

**Comment by natalan** [comment]
+1

**Comment by jamesmorgan** [comment]
+1

**Comment by nobso** [comment]
+1

**Comment by TheSavior** [comment]
It seems like this package might be ready for a fork. Perhaps the @gruntjs org would be willing to take this on.

**Comment by kjhandy** [comment]
+1

**Comment by Miw0** [comment]
Hey guys, just use https://github.com/sindresorhus/grunt-shell which is up-to-date :)

**Comment by gwicksted** [comment]
Fixed in latest release.  Thank you for the PR!

**Pull request closed without merging**
